version: "3.9"

services:
  db:
    image: postgres:16
    container_name: shefport-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - shefport_db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: shefport-app
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    command: ["/bin/bash", "entrypoint.sh"]
    volumes:
      - .:/app

volumes:
  shefport_db_data:

